version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker images...
      - docker build -t ${ECR_REPOSITORY_PREFIX}/frontend:${IMAGE_TAG} ./docker/frontend
      - docker build -t ${ECR_REPOSITORY_PREFIX}/backend:${IMAGE_TAG} ./docker/backend
      - docker build -t ${ECR_REPOSITORY_PREFIX}/axon-server:${IMAGE_TAG} ./docker/axon-server
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push ${ECR_REPOSITORY_PREFIX}/frontend:${IMAGE_TAG}
      - docker push ${ECR_REPOSITORY_PREFIX}/backend:${IMAGE_TAG}
      - docker push ${ECR_REPOSITORY_PREFIX}/axon-server:${IMAGE_TAG}
      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s"}' ${ECR_REPOSITORY_PREFIX}/frontend:${IMAGE_TAG} > imageDefinitions.json
