apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compliance
  template:
    metadata:
      labels:
        app: compliance
    spec:
      containers:
      - name: compliance
        image: 637423471201.dkr.ecr.us-east-1.amazonaws.com/compliance:latest
        ports:
        - containerPort: 8092
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8092
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8092
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: compliance
spec:
  selector:
    app: compliance
  ports:
  - port: 8092
    targetPort: 8092
  type: ClusterIP
