apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging
  template:
    metadata:
      labels:
        app: logging
    spec:
      containers:
      - name: logging
        image: 637423471201.dkr.ecr.us-east-1.amazonaws.com/logging:latest
        ports:
        - containerPort: 8091
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8091
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8091
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: logging
spec:
  selector:
    app: logging
  ports:
  - port: 8091
    targetPort: 8091
  type: ClusterIP
