apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-data
  template:
    metadata:
      labels:
        app: market-data
    spec:
      containers:
      - name: market-data
        image: 637423471201.dkr.ecr.us-east-1.amazonaws.com/market-data:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: market-data
spec:
  selector:
    app: market-data
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
