apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-queue
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-queue
  template:
    metadata:
      labels:
        app: message-queue
    spec:
      containers:
      - name: message-queue
        image: 637423471201.dkr.ecr.us-east-1.amazonaws.com/message-queue:latest
        ports:
        - containerPort: 8090
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: message-queue
spec:
  selector:
    app: message-queue
  ports:
  - port: 8090
    targetPort: 8090
  type: ClusterIP
