apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-management
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-management
  template:
    metadata:
      labels:
        app: portfolio-management
    spec:
      containers:
      - name: portfolio-management
        image: 637423471201.dkr.ecr.us-east-1.amazonaws.com/portfolio-management:latest
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-management
spec:
  selector:
    app: portfolio-management
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
