apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-feed
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-feed
  template:
    metadata:
      labels:
        app: price-feed
    spec:
      containers:
      - name: price-feed
        image: 637423471201.dkr.ecr.us-east-1.amazonaws.com/price-feed:latest
        ports:
        - containerPort: 8085
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: price-feed
spec:
  selector:
    app: price-feed
  ports:
  - port: 8085
    targetPort: 8085
  type: ClusterIP
