apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting
  template:
    metadata:
      labels:
        app: reporting
    spec:
      containers:
      - name: reporting
        image: 637423471201.dkr.ecr.us-east-1.amazonaws.com/reporting:latest
        ports:
        - containerPort: 8094
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8094
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8094
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: reporting
spec:
  selector:
    app: reporting
  ports:
  - port: 8094
    targetPort: 8094
  type: ClusterIP
