apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-management
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risk-management
  template:
    metadata:
      labels:
        app: risk-management
    spec:
      containers:
      - name: risk-management
        image: 637423471201.dkr.ecr.us-east-1.amazonaws.com/risk-management:latest
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: risk-management
spec:
  selector:
    app: risk-management
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP
