apiVersion: apps/v1
kind: Deployment
metadata:
  name: settlement
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: settlement
  template:
    metadata:
      labels:
        app: settlement
    spec:
      containers:
      - name: settlement
        image: 637423471201.dkr.ecr.us-east-1.amazonaws.com/settlement:latest
        ports:
        - containerPort: 8088
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8088
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8088
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: settlement
spec:
  selector:
    app: settlement
  ports:
  - port: 8088
    targetPort: 8088
  type: ClusterIP
