apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-execution
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade-execution
  template:
    metadata:
      labels:
        app: trade-execution
    spec:
      containers:
      - name: trade-execution
        image: 637423471201.dkr.ecr.us-east-1.amazonaws.com/trade-execution:latest
        ports:
        - containerPort: 8095
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8095
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8095
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: trade-execution
spec:
  selector:
    app: trade-execution
  ports:
  - port: 8095
    targetPort: 8095
  type: ClusterIP
