apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-execution
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: trade-execution
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: trade-execution
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: ${DEPLOY_ENV}
          image: ${ECR_REPOSITORY_PREFIX}/trade-execution:latest
          imagePullPolicy: Always
          name: trade-execution
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
